apiVersion: v1
kind: Namespace
metadata:
  name: appns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: appns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

---
kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: appns
  name: podkill
spec:
  schedule: '* * * * *'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - appns
      labelSelectors:
        app: nginx
    mode: all
    action: pod-kill
    duration: 1m
